api-rustco/package-lock.json, api-rustco/package.json
J'ai fait une demande pour cors mais je ne l'avais pas installer alors je l'ai installer
=> Ajouter cors

api-rustco/data/mockUtilisateurs.js, api-rustco/package-lock.json, api-rustco/package.json
Render disait qu'il manquait firebase-admin alors
je l'ai installer
=> Ajouter firebase admin

api-rustco/package-lock.json, api-rustco/package.json
Il manquait le module express-validator alors
je l'ai installé
=> Ajouter express-validator

api-rustco/public/index.html
Ceci permet d'avoir une liste de liens possible
dans l'api sans avoir à chercher dans le code.
=> Créer dossier public et fichier index.html

api-rustco/public/index.html, api-rustco/routes/voitures.js
J'ai modifier l'insertion des données pour qu'ils
corresponde à la db
=> Modifier function ajout dans voitures.js

api-rustco/middlewares/auth.js, api-rustco/package-lock.json, api-rustco/package.json
J'ai installer jsonwebtoken à l'api
=> Ajouter le jsonwebtoken à l'api Closes #50

api-rustco/routes/utilisateurs.js
J'ai changer le code pour qu'il vérifie si le
courriel éxiste déjà au lieu du username
=> Changer le username pour email Closes #61

api-rustco/public/index.html
La route connexion à été ajouter à la page index
de l'api
=> Ajouter route sur page index api Closes #63

api-rustco/routes/voitures.js
Le champ description à été changé dans création
et modification pour avoir description_en et
description_fr.
=> Changer le champ description Closes #68

api-rustco/middlewares/authAdmin.js
J'ai changer le nom du fichier pour que ce sois
plus claire dans le système.
=> Changer le nom du middleware auth.js Closes #70

api-rustco/middlewares/authEmploye.js
Le middleware authEmploye est créer. Il vérifie
si l'utilisateur est un employe OU un admin.
=> Créer le middleware authEmploye Closes #71

api-rustco/routes/utilisateurs.js
J'ai enlever une ligne de code qui allait chercher auth.js, sauf que auth.js n'éxiste plus alors le
Render plantait
=> Enlever une ligne de code dans utilisateurs.js

react-rustco/src/components/App/App.js
La fonction de connexion cherchait dans le form
un input sous le nom de password mais le form
utilise un input sous le nom de mdp
=> Corriger input cherché dans le form

api-rustco/routes/utilisateurs.js
C'est pour tester une théorie sur pourquoi Render
bloque le cors.
=> Modifier ligne res.set pour res.setHeader

api-rustco/routes/utilisateurs.js
J'ai trouver la solution au problème. Le code que
j'avais écrit pour le régler ne servait à rien
alors je l'ai enlevé.
=> Nettoyer code inutile utilisateurs.js Closes #88

api-rustco/app.js
Le code a été ajouté. Je ne sais pas au niveau
connection avec le front-end si ça marche mais
le code créé un produit dans la db de stripe
pour avoir l'option de payer la commande. C'est
fait en allant chercher les voitures dans la db
à partir de leur id, prend leur prix et les
additionnes.
=> Ajouter le code pour stripe Closes #109

react-rustco/src/components/App/App.js
J'ai enlevé le code pour le checkout car j'ai trouver un autre endroit pour le mettre. Le nouvel emplacement sera envoyé dans le prochain commit
=> Enlever le code checkout

api-rustco/app.js
J'avais oublié de créer le code pour calculer le
prix avec le profit pour le checkout.
=> Ajouter code de calcule de profit dans checkout

api-rustco/app.js
Le code pour calculer le prix total de la commande étais mal fait ce qui donnais des prix comme :
112 + 150 = 11 215$
=> Modifier code de calcule de prix Stripe

api-rustco/app.js
Les prix décimales brisait le systèeme
précédent
=> Modifier code de calcul du prix

api-rustco/app.js
J'ai ajouter Number() à quelques endroits
car Render croit que c'est des string et
le résultat devient quelque chose comme:
127111.5$
=> Modifier code de calcule de prix

api-rustco/app.js
J'ai ajouté d'autre Number(). Même problème
que le dernier commit.
=> Modifier code de calcule de prix No 2

api-rustco/routes/commandes.js, api-rustco/routes/utilisateurs.js, api-rustco/routes/voitures.js
J'ai fini le code de validation de la modification des utilisateurs. J'ai aussi prit le temps de
corriger une erreur dans celui de création.
Il faisait un check si prenom était un INT.
=> Ajouter code validation modification utilisateurs

api-rustco/routes/commandes.js, api-rustco/routes/factures.js
J'avais oublier d'ajouter cette ligne de code
ce qui empêchait la modification de savoir
quelle commande modifier.
=> Ajouter idCommande dans fonction modification

react-rustco/src/components/Checkout/Checkout.js, react-rustco/src/components/Succes/Succes.js
facture fonctionnel a lenvoie a la database. et userid aussi.
=> commande et

api-rustco/routes/commandes.js
J'ai fait en sorte que le code prend directement
dans la requête au lieu de la db
=> Changer insertion des voitures dans commandes

api-rustco/routes/voitures.js
La route était en put au lieu de post et la route
était juste :id au lieu de reservation/:id
=> Corriger erreur de code dans toggle reservation

api-rustco/routes/voitures.js
L'idée originale de prendre le id avec
params ne marchait pas comme voulu, alors
on va utilisé la même méthode que création
de factures et commandes. Aussi, l'opérateur
ternaire ne marchait pas alors on vas utiliser
un if.
=> Changer le code pour route de reservation

api-rustco/routes/voitures.js
Le code checkait true dans une string au
lieu de true boolean ce qui causait une
erreur
=> Corriger condition if true dans reservation

api-rustco/routes/voitures.js
=> Enlever authEmployer

api-rustco/routes/voitures.js
La validation prix_acheter bloquait les
décimales alors j'ai enlever la regex.
Ce n'est pas parfait mais c'est tout
ce que je peux faire avant la présentation
=> Corriger erreur validation voitures.js

react-rustco/src/components/Voiture/Voiture.js
Admin n'a plus le bouton ajouter au panier
=> Ajouter code pour disable bouton ajout panier
